tosca_definitions_version: tosca_simple_yaml_1_3

metadata:
  template_name: tosca-kubernetes-types
  template_author: shishqa
  template_version: 1.0.0

description: >-
  TODO

node_types:

  michman.nodes.Kubernetes.Resource:
    derived_from: tosca.nodes.Root
    requirements:
      - host:
          capability: tosca.capabilities.Container
          node: michman.nodes.Kubernetes
          relationship: tosca.relationships.HostedOn

  michman.nodes.Kubernetes.Resource.Pod:
    derived_from: michman.nodes.Kubernetes.Resource
    capabilities:
      pod:
        type: tosca.capabilities.Container
        valid_source_types: [ tosca.nodes.Container.Application ]
